/**
 * DB access functions for the commission_records table.
 *
 * commission_records stores one row per contributor per placement per calculation run.
 * gross_amount and net_payable are BYTEA columns encrypted via FieldEncryptor.
 *
 * Canonical docs:
 *   - docs/prd.md §5.3 — Commission Calculation
 *   - docs/architecture/decisions.md — ER Diagram (commission_records)
 *   - packages/db/schema.sql — commission_records DDL
 *
 * Issue: feat: commission calculation engine (#10)
 */

import type { Sql } from 'postgres';
import { FieldEncryptor } from './encryption.js';
import { createKmsAdapter } from './kms.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type CommissionRecordStatus =
  | 'Accrued'
  | 'PendingApproval'
  | 'Approved'
  | 'Held'
  | 'Payable'
  | 'Paid'
  | 'ClawbackInitiated'
  | 'Recovered';

export interface CommissionRecordRow {
  id: string;
  orgId: string;
  placementId: string;
  contributorId: string;
  planVersionId: string;
  /** Decrypted gross commission amount as a string, e.g. "25000.00" */
  grossAmount: string;
  /** Decrypted net payable amount as a string, e.g. "20000.00" */
  netPayable: string;
  /** Tier rate applied, e.g. 0.25 = 25%. Null when base rate used. */
  tierRate: number | null;
  status: CommissionRecordStatus;
  approvalActor: string | null;
  approvalAt: Date | null;
  createdAt: Date;
  /**
   * Plain-language explanation of this commission calculation.
   * Null for records created before issue #11 landed.
   */
  explanation: string | null;
  /**
   * Hold reason for Held records.
   * Values: 'collection_gate' | 'guarantee_hold' | null.
   * Issue: feat: invoice and collection tracking (#12)
   */
  holdReason: string | null;
}

export interface CreateCommissionRecordInput {
  orgId: string;
  placementId: string;
  contributorId: string;
  planVersionId: string;
  /** Gross commission amount as a numeric string or number. */
  grossAmount: number | string;
  /** Net payable amount as a numeric string or number. */
  netPayable: number | string;
  /** Tier rate applied (decimal fraction, e.g. 0.25). Null when none applied. */
  tierRate?: number | null;
  status: CommissionRecordStatus;
  /**
   * Plain-language explanation generated by the explanation engine.
   * When provided, stored in the explanation column for retrieval by GET /commission-records/:id.
   */
  explanation?: string | null;
  /**
   * Hold reason for Held records.
   * Values: 'collection_gate' | 'guarantee_hold' | null.
   * Issue: feat: invoice and collection tracking (#12)
   */
  holdReason?: string | null;
}

// ---------------------------------------------------------------------------
// Encryptor singleton (lazy-initialised)
// ---------------------------------------------------------------------------

let _encryptor: FieldEncryptor | null = null;

async function getEncryptor(): Promise<FieldEncryptor> {
  if (_encryptor) return _encryptor;
  const adapter = await createKmsAdapter();
  _encryptor = new FieldEncryptor(adapter);
  return _encryptor;
}

/** Replace the encryptor singleton. Used in tests to inject a test adapter. */
export function _setEncryptorForTest(enc: FieldEncryptor): void {
  _encryptor = enc;
}

/** Reset the encryptor singleton. Used in tests for isolation. */
export function _resetEncryptorForTest(): void {
  _encryptor = null;
}

// ---------------------------------------------------------------------------
// createCommissionRecord — encrypt sensitive fields then INSERT
// ---------------------------------------------------------------------------

/**
 * Inserts a new commission_records row, encrypting grossAmount and netPayable
 * as BYTEA before writing to Postgres.
 *
 * Returns the newly created record with decrypted field values.
 */
export async function createCommissionRecord(
  sql: Sql,
  input: CreateCommissionRecordInput,
): Promise<CommissionRecordRow> {
  const enc = await getEncryptor();

  const grossAmountStr = String(input.grossAmount);
  const netPayableStr = String(input.netPayable);

  const grossAmountBuf = await enc.encrypt('commission_records', 'gross_amount', grossAmountStr);
  const netPayableBuf = await enc.encrypt('commission_records', 'net_payable', netPayableStr);

  const tierRateClause = input.tierRate != null ? `${input.tierRate}` : 'NULL';

  // Explanation is stored as plain text (not encrypted — it contains no PII, only amounts and IDs).
  const explanationClause =
    input.explanation != null ? `'${input.explanation.replace(/'/g, "''")}'` : 'NULL';

  const holdReasonClause =
    input.holdReason != null ? `'${input.holdReason.replace(/'/g, "''")}'` : 'NULL';

  const rows = await sql.unsafe(
    `
    INSERT INTO commission_records (
      org_id, placement_id, contributor_id, plan_version_id,
      gross_amount, net_payable, tier_rate, status, explanation, hold_reason
    ) VALUES (
      '${input.orgId}', '${input.placementId}', '${input.contributorId}', '${input.planVersionId}',
      $1, $2, ${tierRateClause}, '${input.status}', ${explanationClause}, ${holdReasonClause}
    )
    RETURNING id, org_id, placement_id, contributor_id, plan_version_id,
              gross_amount, net_payable, tier_rate, status,
              approval_actor, approval_at, created_at, explanation, hold_reason
    `,
    [grossAmountBuf, netPayableBuf],
  );

  if (!rows || rows.length === 0) {
    throw new Error('createCommissionRecord: insert returned no rows');
  }

  return decryptRecordRow(enc, rows[0] as unknown as CommissionRecordRawRow);
}

// ---------------------------------------------------------------------------
// listCommissionRecords — SELECT all records for a placement
// ---------------------------------------------------------------------------

/**
 * Lists all commission records for a given placement, ordered by created_at descending.
 * Decrypts BYTEA columns transparently.
 */
export async function listCommissionRecords(
  sql: Sql,
  orgId: string,
  placementId: string,
): Promise<CommissionRecordRow[]> {
  const enc = await getEncryptor();

  const rows = await sql.unsafe(
    `
    SELECT id, org_id, placement_id, contributor_id, plan_version_id,
           gross_amount, net_payable, tier_rate, status,
           approval_actor, approval_at, created_at, explanation, hold_reason
    FROM commission_records
    WHERE org_id = $1 AND placement_id = $2
    ORDER BY created_at DESC
    `,
    [orgId, placementId],
  );

  if (!rows || rows.length === 0) return [];
  return Promise.all(
    (rows as unknown as CommissionRecordRawRow[]).map((row) => decryptRecordRow(enc, row)),
  );
}

// ---------------------------------------------------------------------------
// getCommissionRecord — SELECT a single record by ID
// ---------------------------------------------------------------------------

/**
 * Fetches a single commission record by ID, scoped to org.
 * Returns null if not found.
 */
export async function getCommissionRecord(
  sql: Sql,
  orgId: string,
  recordId: string,
): Promise<CommissionRecordRow | null> {
  const enc = await getEncryptor();

  const rows = await sql.unsafe(
    `
    SELECT id, org_id, placement_id, contributor_id, plan_version_id,
           gross_amount, net_payable, tier_rate, status,
           approval_actor, approval_at, created_at, explanation, hold_reason
    FROM commission_records
    WHERE id = $1 AND org_id = $2
    LIMIT 1
    `,
    [recordId, orgId],
  );

  if (!rows || rows.length === 0) return null;
  return decryptRecordRow(enc, rows[0] as unknown as CommissionRecordRawRow);
}

// ---------------------------------------------------------------------------
// adjustNetPayable — apply a ledger adjustment to net_payable
// ---------------------------------------------------------------------------

/**
 * Reads the current net_payable for a CommissionRecord, adds adjustmentAmount,
 * and writes the re-encrypted value back.
 *
 * Used by the exception approval workflow to post a ledger adjustment when
 * Finance Admin approves an exception with an impact_amount.
 *
 * Returns the new net_payable value as a string, or null if the record is not found.
 *
 * Issue: feat: exception request and approval workflow (#14)
 */
export async function adjustNetPayable(
  sql: Sql,
  orgId: string,
  recordId: string,
  adjustmentAmount: number,
): Promise<string | null> {
  const enc = await getEncryptor();

  const rows = await sql.unsafe(
    `
    SELECT net_payable FROM commission_records
    WHERE id = $1 AND org_id = $2
    LIMIT 1
    `,
    [recordId, orgId],
  );

  if (!rows || rows.length === 0) return null;

  const row = rows[0] as unknown as { net_payable: Buffer | Uint8Array };
  const currentNetPayable = await enc.decrypt(
    'commission_records',
    'net_payable',
    Buffer.isBuffer(row.net_payable) ? row.net_payable : Buffer.from(row.net_payable),
  );

  const newNetPayable = (parseFloat(currentNetPayable) + adjustmentAmount).toFixed(2);
  const newNetPayableBytes = await enc.encrypt('commission_records', 'net_payable', newNetPayable);

  await sql.unsafe(
    `
    UPDATE commission_records
    SET net_payable = $1
    WHERE id = $2 AND org_id = $3
    `,
    [newNetPayableBytes, recordId, orgId],
  );

  return newNetPayable;
}

// ---------------------------------------------------------------------------
// listCommissionRecordsByContributor — SELECT records for a contributor (producer portal)
// ---------------------------------------------------------------------------

/**
 * Lists all commission records for a given producer (by producer_id / user_id), scoped to org.
 *
 * Joins through the contributors table because commission_records.contributor_id is
 * a foreign key to contributors.id, while the session user is identified by
 * contributors.producer_id (= SessionClaims.user_id).
 *
 * Supports optional status filter (e.g. 'Held').
 *
 * Used by GET /me/commission-records to give producers visibility into their own records.
 *
 * Issue: feat: producer payout statement and deal visibility (#16)
 */
export async function listCommissionRecordsByContributor(
  sql: Sql,
  orgId: string,
  producerId: string,
  statusFilter?: string,
): Promise<CommissionRecordRow[]> {
  const enc = await getEncryptor();

  const rows = await sql.unsafe(
    `
    SELECT cr.id, cr.org_id, cr.placement_id, cr.contributor_id, cr.plan_version_id,
           cr.gross_amount, cr.net_payable, cr.tier_rate, cr.status,
           cr.approval_actor, cr.approval_at, cr.created_at, cr.explanation, cr.hold_reason
    FROM commission_records cr
    JOIN contributors c ON c.id = cr.contributor_id
    WHERE cr.org_id = $1
      AND c.producer_id = $2
      ${statusFilter ? `AND cr.status = '${statusFilter.replace(/'/g, "''")}'` : ''}
    ORDER BY cr.created_at DESC
    `,
    [orgId, producerId],
  );

  if (!rows || rows.length === 0) return [];
  return Promise.all(
    (rows as unknown as CommissionRecordRawRow[]).map((row) => decryptRecordRow(enc, row)),
  );
}

// ---------------------------------------------------------------------------
// listApprovedPayoutsByContributor — SELECT Approved records in Approved runs (producer portal)
// ---------------------------------------------------------------------------

/**
 * Returns commission records for a producer (by producer_id / user_id) that are part
 * of Approved commission runs. Used by GET /me/payouts to show historical approved payouts.
 *
 * Joins through contributors (via contributor_id → contributors.id → producer_id)
 * so the caller can pass SessionClaims.user_id directly.
 *
 * Only records associated with an Approved run are returned (not merely Accrued/Held).
 *
 * Issue: feat: producer payout statement and deal visibility (#16)
 */
export async function listApprovedPayoutsByContributor(
  sql: Sql,
  orgId: string,
  producerId: string,
): Promise<CommissionRecordRow[]> {
  const enc = await getEncryptor();

  const rows = await sql.unsafe(
    `
    SELECT cr.id, cr.org_id, cr.placement_id, cr.contributor_id, cr.plan_version_id,
           cr.gross_amount, cr.net_payable, cr.tier_rate, cr.status,
           cr.approval_actor, cr.approval_at, cr.created_at, cr.explanation, cr.hold_reason
    FROM commission_records cr
    JOIN contributors c ON c.id = cr.contributor_id
    JOIN commission_run_records crr ON crr.commission_record_id = cr.id
    JOIN commission_runs run ON run.id = crr.run_id
    WHERE cr.org_id = $1
      AND c.producer_id = $2
      AND run.status = 'Approved'
    ORDER BY run.approved_at DESC, cr.created_at DESC
    `,
    [orgId, producerId],
  );

  if (!rows || rows.length === 0) return [];
  return Promise.all(
    (rows as unknown as CommissionRecordRawRow[]).map((row) => decryptRecordRow(enc, row)),
  );
}

// ---------------------------------------------------------------------------
// Internal types and helper — decrypt a raw DB row
// ---------------------------------------------------------------------------

interface CommissionRecordRawRow {
  id: string;
  org_id: string;
  placement_id: string;
  contributor_id: string;
  plan_version_id: string;
  gross_amount: Buffer | Uint8Array;
  net_payable: Buffer | Uint8Array;
  tier_rate: string | number | null;
  status: string;
  approval_actor: string | null;
  approval_at: Date | null;
  created_at: Date;
  explanation: string | null;
  hold_reason: string | null;
}

async function decryptRecordRow(
  enc: FieldEncryptor,
  row: CommissionRecordRawRow,
): Promise<CommissionRecordRow> {
  const grossAmount = await enc.decrypt(
    'commission_records',
    'gross_amount',
    Buffer.isBuffer(row.gross_amount) ? row.gross_amount : Buffer.from(row.gross_amount),
  );
  const netPayable = await enc.decrypt(
    'commission_records',
    'net_payable',
    Buffer.isBuffer(row.net_payable) ? row.net_payable : Buffer.from(row.net_payable),
  );

  return {
    id: row.id,
    orgId: row.org_id,
    placementId: row.placement_id,
    contributorId: row.contributor_id,
    planVersionId: row.plan_version_id,
    grossAmount,
    netPayable,
    tierRate: row.tier_rate != null ? Number(row.tier_rate) : null,
    status: row.status as CommissionRecordStatus,
    approvalActor: row.approval_actor ?? null,
    approvalAt: row.approval_at ?? null,
    createdAt: row.created_at,
    explanation: row.explanation ?? null,
    holdReason: row.hold_reason ?? null,
  };
}
